DELETE FROM `scores`;

DELETE FROM `models`;

DELETE FROM `releases`;

INSERT INTO `models` (`slug`,`name`,`provider`,`license`,`status`,`isReasoning`,`contextWindow`,`priceInput`,`priceOutput`) VALUES
('claude-mythos-5','Claude Mythos 5','Anthropic','closed','current',1,'1M+',10,50),
('claude-opus-5','Claude Opus 5','Anthropic','closed','current',1,NULL,5,25),
('claude-fable-5','Claude Fable 5','Anthropic','closed','current',1,'1M+',10,50),
('gpt-5-6-sol','GPT-5.6 Sol','OpenAI','closed','current',1,'1.05M',5,30),
('kimi-k3','Kimi K3','Moonshot AI','closed','current',1,'1.05M',3,15),
('qwen3-8-max','Qwen3.8 Max','Alibaba','open','current',1,'1M',NULL,NULL),
('muse-spark-1-1','Muse Spark 1.1','Meta','closed','superseded',1,'1M',NULL,NULL),
('claude-opus-4-8','Claude Opus 4.8','Anthropic','closed','superseded',1,'1M',5,25),
('gemini-3-6-flash','Gemini 3.6 Flash','Google','closed','superseded',1,'1M',1.5,7.5),
('grok-4-5','Grok 4.5','xAI','closed','superseded',1,'500K',2,6),
('gpt-5-5','GPT-5.5','OpenAI','closed','superseded',1,'1M',5,30),
('gpt-5-4','GPT-5.4','OpenAI','closed','superseded',1,'1.05M',2.5,15),
('gpt-5-6-terra','GPT-5.6 Terra','OpenAI','closed','current',1,'1.05M',2,12),
('claude-opus-4-7','Claude Opus 4.7','Anthropic','closed','current',0,'1M',5,25),
('qwen3-7-max','Qwen3.7 Max','Alibaba','closed','superseded',1,'1M',NULL,NULL),
('muse-spark','Muse Spark','Meta','closed','superseded',1,'262K',NULL,NULL),
('mimo-v2-5-pro','MiMo-V2.5-Pro','Xiaomi','closed','current',1,'1M',NULL,NULL),
('minimax-m3','MiniMax M3','MiniMax','open','current',0,'1M',0.3,1.2),
('hy3','Hy3','Tencent','open','current',1,'256K',0,0),
('claude-opus-4-6','Claude Opus 4.6','Anthropic','closed','superseded',0,'1M',5,25),
('gemini-3-pro','Gemini 3 Pro','Google','closed','superseded',0,'2M',2,12),
('gpt-5-6-luna','GPT-5.6 Luna','OpenAI','closed','current',1,'1.05M',0.2,1.2),
('inkling','Inkling','Thinking Machines Lab','open','current',0,'1M',1.87,4.68),
('mimo-v2-pro','MiMo-V2-Pro','Xiaomi','closed','superseded',1,'1M',NULL,NULL),
('glm-5-1','GLM-5.1','Z.AI','open','superseded',1,NULL,1.4,4.4),
('gpt-5-2-pro','GPT-5.2 Pro','OpenAI','closed','superseded',1,NULL,25,150),
('gpt-5-4-nano','GPT-5.4 nano','OpenAI','closed','superseded',0,NULL,0.2,1.25),
('qwen3-7-plus','Qwen3.7 Plus','Alibaba','closed','superseded',1,NULL,NULL,NULL),
('gpt-5-3-codex','GPT-5.3 Codex','OpenAI','closed','superseded',1,NULL,1.75,14),
('glm-5','GLM-5','Z.AI','open','superseded',1,NULL,1,3.2);

INSERT INTO `models` (`slug`,`name`,`provider`,`license`,`status`,`isReasoning`,`contextWindow`,`priceInput`,`priceOutput`) VALUES
('inkling-small','Inkling-Small','Thinking Machines Lab','open','current',0,NULL,0.58,1.44),
('gemini-3-5-flash-lite','Gemini 3.5 Flash-Lite','Google','closed','superseded',0,NULL,0.3,2.5),
('qwen3-6-plus','Qwen3.6 Plus','Alibaba','closed','superseded',1,NULL,NULL,NULL),
('claude-sonnet-5','Claude Sonnet 5','Anthropic','closed','current',1,'1M',2,10),
('gemini-3-5-flash','Gemini 3.5 Flash','Google','closed','superseded',1,NULL,1.5,9),
('claude-sonnet-4-6','Claude Sonnet 4.6','Anthropic','closed','superseded',1,'1M',3,15),
('gpt-5-5-pro','GPT-5.5 Pro','OpenAI','closed','superseded',1,NULL,30,180),
('grok-4-3','Grok 4.3','xAI','closed','superseded',1,NULL,1.25,2.5),
('claude-opus-4-5','Claude Opus 4.5','Anthropic','closed','superseded',1,'1M',5,25),
('grok-4-6','Grok 4.6','xAI','closed','current',1,'500K',2,6),
('glm-5-2','GLM-5.2','Z.AI','open','current',1,NULL,1.4,4.4),
('minimax-m2-7','MiniMax M2.7','MiniMax','open','superseded',0,NULL,0.3,1.2),
('glm-5v-turbo','GLM-5V-Turbo','Z.AI','closed','current',0,NULL,1.2,4),
('muse-spark-1-2','Muse Spark 1.2','Meta','closed','current',1,NULL,1.25,4.25),
('gemini-3-7-flash','Gemini 3.7 Flash','Google','closed','current',1,'1M',0.75,3.75),
('deepseek-v4-pro-0813','DeepSeek-V4-Pro-0813','DeepSeek','open','current',1,NULL,NULL,NULL),
('deepseek-v4-flash-0731','DeepSeek-V4-Flash-0731','DeepSeek','open','current',1,NULL,NULL,NULL),
('deepseek-v4-pro-preview','DeepSeek-V4-Pro-Preview','DeepSeek','open','superseded',1,NULL,NULL,NULL),
('deepseek-v4-flash-preview','DeepSeek-V4-Flash-Preview','DeepSeek','open','superseded',1,NULL,NULL,NULL),
('deepseek-v4-pro-max','DeepSeek-V4-Pro-Max','DeepSeek','open','current',1,NULL,NULL,NULL),
('deepseek-v4-flash-max','DeepSeek-V4-Flash-Max','DeepSeek','open','current',1,NULL,NULL,NULL),
('kimi-k2-6','Kimi K2.6','Moonshot AI','open','superseded',1,NULL,NULL,NULL),
('kimi-k2-5','Kimi K2.5','Moonshot AI','open','superseded',1,NULL,NULL,NULL),
('gemini-3-1-pro','Gemini 3.1 Pro','Google','closed','superseded',1,NULL,NULL,NULL),
('gemini-3-flash','Gemini 3 Flash','Google','closed','superseded',1,NULL,NULL,NULL),
('claude-mythos-preview','Claude Mythos Preview','Anthropic','closed','superseded',1,NULL,NULL,NULL),
('minimax-m2-5','MiniMax M2.5','MiniMax','open','superseded',0,NULL,NULL,NULL),
('qwen3-6-plus-coding','Qwen3.6 Plus (Coding)','Alibaba','closed','superseded',1,NULL,NULL,NULL),
('gpt-5-2','GPT-5.2','OpenAI','closed','superseded',1,NULL,NULL,NULL),
('step-3-5-flash','Step-3.5-Flash','StepFun','open','current',1,NULL,NULL,NULL);

INSERT INTO `models` (`slug`,`name`,`provider`,`license`,`status`,`isReasoning`,`contextWindow`,`priceInput`,`priceOutput`) VALUES
('glm-4-7','GLM-4.7','Z.AI','open','superseded',1,NULL,NULL,NULL),
('glm-4-7-flash','GLM-4.7-Flash','Z.AI','open','superseded',0,NULL,NULL,NULL),
('mimo-v2-flash','MiMo-V2-Flash','Xiaomi','open','superseded',0,NULL,NULL,NULL),
('nemotron-3-ultra','Nemotron 3 Ultra','NVIDIA','open','current',1,NULL,NULL,NULL),
('claude-haiku-4-5','Claude Haiku 4.5','Anthropic','closed','superseded',0,NULL,NULL,NULL),
('gpt-5','GPT-5','OpenAI','closed','superseded',1,NULL,NULL,NULL),
('ling-3-0-flash','Ling 3.0 Flash','InclusionAI','open','current',0,NULL,NULL,NULL),
('mistral-medium-3-5','Mistral Medium 3.5','Mistral','open','current',0,NULL,NULL,NULL),
('gemini-omni-flash','Gemini Omni Flash','Google','closed','current',1,NULL,NULL,NULL);

INSERT INTO `scores` (`modelId`,`benchmarkId`,`rawScore`,`rawScoreSecondary`,`secondaryLabel`,`benchmarkVersion`,`sourceType`,`sourceName`,`sourceUrl`,`measuredAt`) VALUES
(( SELECT id FROM models WHERE slug='kimi-k3' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),91.2,NULL,NULL,NULL,'self_reported','Steel.dev index → www.kimi.com','https://www.kimi.com/blog/kimi-k3','2026-07-16'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='osworld-2-0' ),62.6,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/gpt-5-6/','2026-07-09'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),90.4,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/gpt-5-6/','2026-07-09'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),82.2,NULL,NULL,NULL,'leaderboard','Steel.dev index → thinkingmachines.ai','https://thinkingmachines.ai/news/introducing-inkling','2026-07-01'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),88,NULL,NULL,NULL,'leaderboard','Steel.dev index → thinkingmachines.ai','https://thinkingmachines.ai/news/introducing-inkling','2026-07-01'),
(( SELECT id FROM models WHERE slug='glm-5-2' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),80,NULL,NULL,NULL,'leaderboard','Steel.dev index → thinkingmachines.ai','https://thinkingmachines.ai/news/introducing-inkling','2026-07-01'),
(( SELECT id FROM models WHERE slug='inkling' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),77.6,NULL,NULL,NULL,'leaderboard','Steel.dev index → thinkingmachines.ai','https://thinkingmachines.ai/news/introducing-inkling','2026-07-01'),
(( SELECT id FROM models WHERE slug='kimi-k2-5' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),76.8,NULL,NULL,NULL,'leaderboard','Steel.dev index → thinkingmachines.ai','https://thinkingmachines.ai/news/introducing-inkling','2026-07-01'),
(( SELECT id FROM models WHERE slug='nemotron-3-ultra' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),70.7,NULL,NULL,NULL,'leaderboard','Steel.dev index → thinkingmachines.ai','https://thinkingmachines.ai/news/introducing-inkling','2026-07-01'),
(( SELECT id FROM models WHERE slug='inkling' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),77.1,NULL,NULL,NULL,'leaderboard','Steel.dev index → thinkingmachines.ai','https://thinkingmachines.ai/news/introducing-inkling','2026-07-01'),
(( SELECT id FROM models WHERE slug='claude-sonnet-5' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),81.2,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/9e6a1044980d8c4ed85669faf9c2a8342e2e9f1e/Claude%20Sonnet%205%20System%20Card.pdf','2026-06-30'),
(( SELECT id FROM models WHERE slug='claude-sonnet-4-6' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),78.5,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/9e6a1044980d8c4ed85669faf9c2a8342e2e9f1e/Claude%20Sonnet%205%20System%20Card.pdf','2026-06-30'),
(( SELECT id FROM models WHERE slug='claude-sonnet-5' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),84.7,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/9e6a1044980d8c4ed85669faf9c2a8342e2e9f1e/Claude%20Sonnet%205%20System%20Card.pdf','2026-06-30'),
(( SELECT id FROM models WHERE slug='claude-sonnet-4-6' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),76.2,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/9e6a1044980d8c4ed85669faf9c2a8342e2e9f1e/Claude%20Sonnet%205%20System%20Card.pdf','2026-06-30'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='draco' ),65.3,NULL,NULL,NULL,'leaderboard','Steel.dev index → openrouter.ai','https://openrouter.ai/blog/announcements/fusion-beats-frontier/','2026-06-12'),
(( SELECT id FROM models WHERE slug='claude-mythos-5' ),( SELECT id FROM benchmarks WHERE slug='draco' ),86.4,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/claude-fable-5-mythos-5-system-card','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-mythos-5' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),95.5,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/d00db56fa754a1b115b6dd7cb2e3c342ee809620.pdf','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-mythos-preview' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),85.4,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/d00db56fa754a1b115b6dd7cb2e3c342ee809620.pdf','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-mythos-preview' ),( SELECT id FROM benchmarks WHERE slug='draco' ),83.6,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/claude-fable-5-mythos-5-system-card','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),95,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/d00db56fa754a1b115b6dd7cb2e3c342ee809620.pdf','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-mythos-5' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),85,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/d00db56fa754a1b115b6dd7cb2e3c342ee809620.pdf','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='draco' ),80.4,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/0f0c97ad20d8005706296bd92aa1c27c6b2f4f61/Claude%20Opus%204.8%20System%20Card.pdf','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),85,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/d00db56fa754a1b115b6dd7cb2e3c342ee809620.pdf','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='osworld-2-0' ),49.33,NULL,NULL,NULL,'leaderboard','Steel.dev index → osworld-v2.xlang.ai','https://osworld-v2.xlang.ai/','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-opus-4-7' ),( SELECT id FROM benchmarks WHERE slug='osworld-2-0' ),49.1,NULL,NULL,NULL,'leaderboard','Steel.dev index → osworld-v2.xlang.ai','https://osworld-v2.xlang.ai/','2026-06-01'),
(( SELECT id FROM models WHERE slug='claude-mythos-5' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),88,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/d00db56fa754a1b115b6dd7cb2e3c342ee809620.pdf','2026-06-01'),
(( SELECT id FROM models WHERE slug='minimax-m3' ),( SELECT id FROM benchmarks WHERE slug='osworld-2-0' ),22.3,NULL,NULL,NULL,'leaderboard','Steel.dev index → osworld-v2.xlang.ai','https://osworld-v2.xlang.ai/','2026-06-01'),
(( SELECT id FROM models WHERE slug='minimax-m3' ),( SELECT id FROM benchmarks WHERE slug='draco' ),73.23,NULL,NULL,NULL,'self_reported','Steel.dev index → www.minimax.io','https://www.minimax.io/blog/minimax-m3','2026-05-31'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),88.6,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-opus-4-8','2026-05-28'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),83.4,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-opus-4-8','2026-05-28'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),84.3,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-opus-4-8','2026-05-28'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-max' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),80.6,NULL,NULL,NULL,'self_reported','Steel.dev index → huggingface.co','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro/','2026-04-24'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-max' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),83.4,NULL,NULL,NULL,'self_reported','Steel.dev index → huggingface.co','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-04-24'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-max' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),79,NULL,NULL,NULL,'self_reported','Steel.dev index → huggingface.co','https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash','2026-04-24'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-max' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),73.2,NULL,NULL,NULL,'self_reported','Steel.dev index → huggingface.co','https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash','2026-04-24'),
(( SELECT id FROM models WHERE slug='kimi-k2-6' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),86.3,NULL,NULL,NULL,'self_reported','Steel.dev index → www.kimi.com','https://www.kimi.com/blog/kimi-k2-6','2026-04-20'),
(( SELECT id FROM models WHERE slug='kimi-k2-6' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),80.2,NULL,NULL,NULL,'self_reported','Steel.dev index → www.kimi.com','https://www.kimi.com/blog/kimi-k2-6','2026-04-20'),
(( SELECT id FROM models WHERE slug='claude-opus-4-7' ),( SELECT id FROM benchmarks WHERE slug='draco' ),77.7,NULL,NULL,NULL,'self_reported','Steel.dev index → www-cdn.anthropic.com','https://www-cdn.anthropic.com/037f06850df7fbe871e206dad004c3db5fd50340/Claude%20Opus%204.7%20System%20Card.pdf','2026-04-16'),
(( SELECT id FROM models WHERE slug='claude-opus-4-7' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),87.6,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-opus-4-7','2026-04-16'),
(( SELECT id FROM models WHERE slug='claude-opus-4-7' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),79.3,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-opus-4-7','2026-04-16');

INSERT INTO `scores` (`modelId`,`benchmarkId`,`rawScore`,`rawScoreSecondary`,`secondaryLabel`,`benchmarkVersion`,`sourceType`,`sourceName`,`sourceUrl`,`measuredAt`) VALUES
(( SELECT id FROM models WHERE slug='claude-mythos-preview' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),93.9,NULL,NULL,NULL,'leaderboard','Steel.dev index → www.mindstudio.ai','https://www.mindstudio.ai/blog/claude-mythos-benchmark-results-swe-bench-agentic-coding','2026-04-09'),
(( SELECT id FROM models WHERE slug='claude-mythos-preview' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),86.9,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/glasswing','2026-04-07'),
(( SELECT id FROM models WHERE slug='claude-opus-4-6' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),83.7,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/glasswing','2026-04-07'),
(( SELECT id FROM models WHERE slug='qwen3-6-plus' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),78.8,NULL,NULL,NULL,'self_reported','Steel.dev index → qwen.ai','https://qwen.ai/blog?id=qwen3.6','2026-04-02'),
(( SELECT id FROM models WHERE slug='gpt-5-5-pro' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),90.1,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/introducing-gpt-5-5/','2026-04-01'),
(( SELECT id FROM models WHERE slug='glm-5v-turbo' ),( SELECT id FROM benchmarks WHERE slug='webvoyager' ),88.5,NULL,NULL,NULL,'self_reported','Steel.dev index → docs.z.ai','https://docs.z.ai/guides/vlm/glm-5v-turbo','2026-04-01'),
(( SELECT id FROM models WHERE slug='gpt-5-5' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),84.4,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/introducing-gpt-5-5/','2026-04-01'),
(( SELECT id FROM models WHERE slug='glm-5v-turbo' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),62.3,NULL,NULL,NULL,'self_reported','Steel.dev index → docs.z.ai','https://docs.z.ai/guides/vlm/glm-5v-turbo','2026-04-01'),
(( SELECT id FROM models WHERE slug='glm-5-1' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),79.3,NULL,NULL,NULL,'self_reported','Steel.dev index → docs.z.ai','https://docs.z.ai/guides/llm/glm-5.1','2026-04-01'),
(( SELECT id FROM models WHERE slug='minimax-m2-5' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),76.3,NULL,NULL,NULL,'self_reported','Steel.dev index → www.minimax.io','https://www.minimax.io/news/minimax-m25','2026-04-01'),
(( SELECT id FROM models WHERE slug='mimo-v2-pro' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),78,NULL,NULL,NULL,'self_reported','Steel.dev index → mimo.xiaomi.com','https://mimo.xiaomi.com/mimo-v2-pro','2026-03-18'),
(( SELECT id FROM models WHERE slug='gpt-5-4' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),75,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/introducing-gpt-5-4/','2026-03-05'),
(( SELECT id FROM models WHERE slug='gpt-5-4' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),82.7,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/introducing-gpt-5-4/','2026-03-05'),
(( SELECT id FROM models WHERE slug='gemini-3-1-pro' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),80.6,NULL,NULL,NULL,'self_reported','Steel.dev index → deepmind.google','https://deepmind.google/models/gemini/pro/','2026-02-19'),
(( SELECT id FROM models WHERE slug='gemini-3-1-pro' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),85.9,NULL,NULL,NULL,'self_reported','Steel.dev index → storage.googleapis.com','https://storage.googleapis.com/deepmind-media/gemini/gemini_3-1_pro_model_evaluation.pdf','2026-02-19'),
(( SELECT id FROM models WHERE slug='gemini-3-pro' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),59.2,NULL,NULL,NULL,'self_reported','Steel.dev index → deepmind.google','https://deepmind.google/models/model-cards/gemini-3-1-pro/','2026-02-19'),
(( SELECT id FROM models WHERE slug='claude-sonnet-4-6' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),79.6,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-sonnet-4-6','2026-02-17'),
(( SELECT id FROM models WHERE slug='claude-opus-4-6' ),( SELECT id FROM benchmarks WHERE slug='draco' ),59.8,NULL,NULL,NULL,'leaderboard','Steel.dev index → arxiv.org','https://arxiv.org/abs/2602.11685','2026-02-12'),
(( SELECT id FROM models WHERE slug='minimax-m2-5' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),80.2,NULL,NULL,NULL,'self_reported','Steel.dev index → www.minimax.io','https://www.minimax.io/news/minimax-m25','2026-02-12'),
(( SELECT id FROM models WHERE slug='claude-opus-4-5' ),( SELECT id FROM benchmarks WHERE slug='draco' ),46.7,NULL,NULL,NULL,'leaderboard','Steel.dev index → arxiv.org','https://arxiv.org/abs/2602.11685','2026-02-12'),
(( SELECT id FROM models WHERE slug='glm-5' ),( SELECT id FROM benchmarks WHERE slug='tau-bench' ),63.2,NULL,NULL,NULL,'leaderboard','Steel.dev index → taubench.com','https://taubench.com/','2026-02-11'),
(( SELECT id FROM models WHERE slug='glm-5' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),77.8,NULL,NULL,NULL,'self_reported','Steel.dev index → docs.z.ai','https://docs.z.ai/guides/llm/glm-5','2026-02-11'),
(( SELECT id FROM models WHERE slug='claude-opus-4-6' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),80.8,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-opus-4-6','2026-02-05'),
(( SELECT id FROM models WHERE slug='claude-opus-4-6' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),72.7,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/glasswing','2026-02-05'),
(( SELECT id FROM models WHERE slug='kimi-k2-5' ),( SELECT id FROM benchmarks WHERE slug='webarena' ),58.9,NULL,NULL,NULL,'leaderboard','Steel.dev index → arxiv.org','https://arxiv.org/html/2602.02276v1','2026-02-01'),
(( SELECT id FROM models WHERE slug='kimi-k2-5' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),78.4,NULL,NULL,NULL,'leaderboard','Steel.dev index → huggingface.co','https://huggingface.co/moonshotai/Kimi-K2.5','2026-02-01'),
(( SELECT id FROM models WHERE slug='glm-5' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),75.9,NULL,NULL,NULL,'self_reported','Steel.dev index → docs.z.ai','https://docs.z.ai/guides/llm/glm-5','2026-02-01'),
(( SELECT id FROM models WHERE slug='step-3-5-flash' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),69,NULL,NULL,NULL,'leaderboard','Steel.dev index → arxiv.org','https://arxiv.org/abs/2602.10604','2026-02-01'),
(( SELECT id FROM models WHERE slug='glm-4-7-flash' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),42.8,NULL,NULL,NULL,'self_reported','Steel.dev index → docs.z.ai','https://docs.z.ai/guides/llm/glm-4.7','2026-02-01'),
(( SELECT id FROM models WHERE slug='step-3-5-flash' ),( SELECT id FROM benchmarks WHERE slug='tau-bench' ),88.2,NULL,NULL,NULL,'leaderboard','Steel.dev index → arxiv.org','https://arxiv.org/abs/2602.10604','2026-01-29'),
(( SELECT id FROM models WHERE slug='kimi-k2-5' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),63.3,NULL,NULL,NULL,'leaderboard','Steel.dev index → arxiv.org','https://arxiv.org/html/2602.02276v1','2026-01-27'),
(( SELECT id FROM models WHERE slug='mimo-v2-flash' ),( SELECT id FROM benchmarks WHERE slug='tau-bench' ),80.3,NULL,NULL,NULL,'leaderboard','Steel.dev index → arxiv.org','https://arxiv.org/abs/2601.02780','2026-01-06'),
(( SELECT id FROM models WHERE slug='mimo-v2-flash' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),58.3,NULL,NULL,NULL,'leaderboard','Steel.dev index → huggingface.co','https://huggingface.co/XiaomiMiMo/MiMo-V2-Flash-Base','2026-01-01'),
(( SELECT id FROM models WHERE slug='glm-4-7' ),( SELECT id FROM benchmarks WHERE slug='tau-bench' ),87.4,NULL,NULL,NULL,'self_reported','Steel.dev index → docs.z.ai','https://docs.z.ai/guides/llm/glm-4.7','2025-12-22'),
(( SELECT id FROM models WHERE slug='glm-4-7-flash' ),( SELECT id FROM benchmarks WHERE slug='tau-bench' ),79.5,NULL,NULL,NULL,'leaderboard','Steel.dev index → inference-docs.cerebras.ai','https://inference-docs.cerebras.ai/resources/glm-47-migration','2025-12-22'),
(( SELECT id FROM models WHERE slug='gemini-3-flash' ),( SELECT id FROM benchmarks WHERE slug='tau-bench' ),67.8,NULL,NULL,NULL,'self_reported','Steel.dev index → storage.googleapis.com','https://storage.googleapis.com/deepmind-media/gemini/gemini_3_pro_model_evaluation.pdf','2025-12-17'),
(( SELECT id FROM models WHERE slug='gemini-3-flash' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),78,NULL,NULL,NULL,'self_reported','Steel.dev index → blog.google','https://blog.google/products/gemini/gemini-3-flash/','2025-12-17'),
(( SELECT id FROM models WHERE slug='gpt-5-2' ),( SELECT id FROM benchmarks WHERE slug='tau-bench' ),69.9,NULL,NULL,NULL,'leaderboard','Steel.dev index → taubench.com','https://taubench.com','2025-12-11'),
(( SELECT id FROM models WHERE slug='gpt-5-2' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),80,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/introducing-gpt-5-2/','2025-12-11'),
(( SELECT id FROM models WHERE slug='gpt-5-2-pro' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),77.9,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/introducing-gpt-5-2/','2025-12-11');

INSERT INTO `scores` (`modelId`,`benchmarkId`,`rawScore`,`rawScoreSecondary`,`secondaryLabel`,`benchmarkVersion`,`sourceType`,`sourceName`,`sourceUrl`,`measuredAt`) VALUES
(( SELECT id FROM models WHERE slug='gpt-5-2' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),65.8,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/introducing-gpt-5-2/','2025-12-11'),
(( SELECT id FROM models WHERE slug='glm-4-7' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),67.5,NULL,NULL,NULL,'self_reported','Steel.dev index → docs.z.ai','https://docs.z.ai/guides/llm/glm-4.7','2025-12-01'),
(( SELECT id FROM models WHERE slug='claude-opus-4-5' ),( SELECT id FROM benchmarks WHERE slug='tau-bench' ),70.2,NULL,NULL,NULL,'leaderboard','Steel.dev index → taubench.com','https://taubench.com','2025-11-24'),
(( SELECT id FROM models WHERE slug='claude-opus-4-5' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-verified' ),80.9,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-opus-4-5','2025-11-24'),
(( SELECT id FROM models WHERE slug='claude-opus-4-5' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),66.3,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-opus-4-5','2025-11-24'),
(( SELECT id FROM models WHERE slug='gemini-3-pro' ),( SELECT id FROM benchmarks WHERE slug='tau-bench' ),65.8,NULL,NULL,NULL,'self_reported','Steel.dev index → storage.googleapis.com','https://storage.googleapis.com/deepmind-media/gemini/gemini_3_pro_model_evaluation.pdf','2025-11-18'),
(( SELECT id FROM models WHERE slug='claude-haiku-4-5' ),( SELECT id FROM benchmarks WHERE slug='osworld-verified' ),50.7,NULL,NULL,NULL,'self_reported','Steel.dev index → www.anthropic.com','https://www.anthropic.com/news/claude-haiku-4-5','2025-10-15'),
(( SELECT id FROM models WHERE slug='gpt-5' ),( SELECT id FROM benchmarks WHERE slug='browsecomp' ),54.9,NULL,NULL,NULL,'self_reported','Steel.dev index → openai.com','https://openai.com/index/gpt-5/','2025-08-01'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),61,NULL,NULL,NULL,'self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),56,NULL,NULL,NULL,'self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),61,NULL,NULL,NULL,'third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),62,NULL,NULL,NULL,'third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='gdpval' ),1753,NULL,NULL,'GDPVal-AA v2','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='gdpval' ),1526,NULL,NULL,'GDPVal-AA v2','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='gdpval' ),1728,NULL,NULL,'GDPVal-AA v2','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='gdpval' ),1741,NULL,NULL,'GDPVal-AA v2','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='cursorbench' ),69.9,NULL,NULL,'v3.2','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='cursorbench' ),66.7,NULL,NULL,'v3.2','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='cursorbench' ),67.2,NULL,NULL,'v3.2','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='cursorbench' ),70.5,NULL,NULL,'v3.2','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='deepswe' ),65.9,NULL,NULL,'v1.1','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='deepswe' ),54,NULL,NULL,'v1.1','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='deepswe' ),73,NULL,NULL,'v1.1','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='deepswe' ),70,NULL,NULL,'v1.1','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='frontiercode' ),61.3,NULL,NULL,'v1.1 (Extended)','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='frontiercode' ),56.6,NULL,NULL,'v1.1 (Extended)','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='frontiercode' ),60.6,NULL,NULL,'v1.1 (Extended)','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='frontiercode' ),64.9,NULL,NULL,'v1.1 (Extended)','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='apex-agents' ),57.5,NULL,NULL,NULL,'self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='apex-agents' ),47.1,NULL,NULL,NULL,'self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='apex-agents' ),56.7,NULL,NULL,NULL,'third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='apex-agents' ),59.2,NULL,NULL,NULL,'third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-3-0' ),26,NULL,NULL,'v3.0','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-3-0' ),15.7,NULL,NULL,'v3.0','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-3-0' ),34.6,NULL,NULL,'v3.0','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-3-0' ),34.1,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='apex-swe' ),56.4,NULL,NULL,NULL,'self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='apex-swe' ),53.6,NULL,NULL,NULL,'self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='apex-swe' ),58.8,NULL,NULL,NULL,'third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='aa-briefcase' ),1577,NULL,NULL,NULL,'self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14');

INSERT INTO `scores` (`modelId`,`benchmarkId`,`rawScore`,`rawScoreSecondary`,`secondaryLabel`,`benchmarkVersion`,`sourceType`,`sourceName`,`sourceUrl`,`measuredAt`) VALUES
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='aa-briefcase' ),1313,NULL,NULL,NULL,'self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='aa-briefcase' ),1502,NULL,NULL,NULL,'third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='aa-briefcase' ),1574,NULL,NULL,NULL,'third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='harvey-lab' ),15.8,NULL,NULL,'Vals','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='harvey-lab' ),12.9,NULL,NULL,'Vals','self_reported','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='harvey-lab' ),2.5,NULL,NULL,'Vals','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='harvey-lab' ),11.3,NULL,NULL,'Vals','third_party','xAI Grok 4.6 release table','https://x.ai/news/grok-4-6','2026-08-14'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-0813' ),( SELECT id FROM benchmarks WHERE slug='humanity-s-last-exam' ),42.7,60,'with tools',NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-0731' ),( SELECT id FROM benchmarks WHERE slug='humanity-s-last-exam' ),37.8,51.5,'with tools',NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-preview' ),( SELECT id FROM benchmarks WHERE slug='humanity-s-last-exam' ),37.7,48.2,'with tools',NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-preview' ),( SELECT id FROM benchmarks WHERE slug='humanity-s-last-exam' ),34.8,45.1,'with tools',NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='humanity-s-last-exam' ),49.8,57.9,'with tools',NULL,'third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='humanity-s-last-exam' ),53.3,63,'with tools',NULL,'third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-0813' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-2-1' ),87.9,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-0731' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-2-1' ),82.7,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-preview' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-2-1' ),72.1,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-preview' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-2-1' ),61.8,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-2-1' ),85,NULL,NULL,NULL,'third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='terminal-bench-2-1' ),88,NULL,NULL,NULL,'third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-0813' ),( SELECT id FROM benchmarks WHERE slug='nl2repo-bench' ),61.5,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-0731' ),( SELECT id FROM benchmarks WHERE slug='nl2repo-bench' ),54.2,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-preview' ),( SELECT id FROM benchmarks WHERE slug='nl2repo-bench' ),38.5,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-preview' ),( SELECT id FROM benchmarks WHERE slug='nl2repo-bench' ),39.4,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='nl2repo-bench' ),69.7,NULL,NULL,NULL,'third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-0813' ),( SELECT id FROM benchmarks WHERE slug='cybergym' ),83.3,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-0731' ),( SELECT id FROM benchmarks WHERE slug='cybergym' ),76.7,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-preview' ),( SELECT id FROM benchmarks WHERE slug='cybergym' ),52.7,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-preview' ),( SELECT id FROM benchmarks WHERE slug='cybergym' ),38.7,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='cybergym' ),78.3,NULL,NULL,NULL,'third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='cybergym' ),83.1,NULL,NULL,NULL,'third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-0813' ),( SELECT id FROM benchmarks WHERE slug='deepswe' ),62.7,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-0731' ),( SELECT id FROM benchmarks WHERE slug='deepswe' ),54.4,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-preview' ),( SELECT id FROM benchmarks WHERE slug='deepswe' ),12.8,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-preview' ),( SELECT id FROM benchmarks WHERE slug='deepswe' ),7.3,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='deepswe' ),58,NULL,NULL,NULL,'third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-0813' ),( SELECT id FROM benchmarks WHERE slug='toolathlon' ),74.1,NULL,NULL,'Verified','self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-0731' ),( SELECT id FROM benchmarks WHERE slug='toolathlon' ),70.3,NULL,NULL,'Verified','self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-preview' ),( SELECT id FROM benchmarks WHERE slug='toolathlon' ),55.9,NULL,NULL,'Verified','self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-preview' ),( SELECT id FROM benchmarks WHERE slug='toolathlon' ),49.7,NULL,NULL,'Verified','self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='toolathlon' ),76.2,NULL,NULL,'Verified','third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13');

INSERT INTO `scores` (`modelId`,`benchmarkId`,`rawScore`,`rawScoreSecondary`,`secondaryLabel`,`benchmarkVersion`,`sourceType`,`sourceName`,`sourceUrl`,`measuredAt`) VALUES
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='toolathlon' ),77.9,NULL,NULL,'Verified','third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-0813' ),( SELECT id FROM benchmarks WHERE slug='agents-last-exam' ),25.7,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-0731' ),( SELECT id FROM benchmarks WHERE slug='agents-last-exam' ),25.2,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-preview' ),( SELECT id FROM benchmarks WHERE slug='agents-last-exam' ),16.5,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-preview' ),( SELECT id FROM benchmarks WHERE slug='agents-last-exam' ),15.8,NULL,NULL,NULL,'self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='agents-last-exam' ),25.7,NULL,NULL,NULL,'third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-0813' ),( SELECT id FROM benchmarks WHERE slug='automationbench' ),31.8,NULL,NULL,'Public','self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-0731' ),( SELECT id FROM benchmarks WHERE slug='automationbench' ),25.1,NULL,NULL,'Public','self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-preview' ),( SELECT id FROM benchmarks WHERE slug='automationbench' ),12.8,NULL,NULL,'Public','self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-preview' ),( SELECT id FROM benchmarks WHERE slug='automationbench' ),10.8,NULL,NULL,'Public','self_reported','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='automationbench' ),27.2,NULL,NULL,'Public','third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='automationbench' ),29.1,NULL,NULL,'Public','third_party','DeepSeek V4 Pro release table','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro','2026-08-13'),
(( SELECT id FROM models WHERE slug='claude-opus-5' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),67.21,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='gemini-3-7-flash' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),59.31,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='kimi-k3' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),57.81,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='muse-spark-1-2' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),57.05,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='deepseek-v4-flash-0731' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),53.57,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='glm-5-2' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),53.12,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='qwen3-8-max' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),51.84,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='minimax-m3' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),42.72,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='mimo-v2-5-pro' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),40.97,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='inkling' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),34.1,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='nemotron-3-ultra' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),27.39,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='ling-3-0-flash' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),21.7,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='mistral-medium-3-5' ),( SELECT id FROM benchmarks WHERE slug='artificial-analysis-intelligence-index' ),17.95,NULL,NULL,'Vals Index 2026-08-14','third_party','Vals AI Vals Index (independent)','https://www.vals.ai/home','2026-08-14'),
(( SELECT id FROM models WHERE slug='claude-opus-5' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),93.4,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),83.6,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-mythos-5' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),93.9,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='kimi-k3' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),84.8,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='qwen3-8-max' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),66.5,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gemini-3-7-flash' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),67.4,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-opus-5' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),90.4,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),93,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='qwen3-8-max' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),94.3,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),71.2,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='deepseek-v4-pro-max' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),93.5,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),80.8,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),78.7,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5' ),( SELECT id FROM benchmarks WHERE slug='swe-bench-pro' ),23.3,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-mythos-5' ),( SELECT id FROM benchmarks WHERE slug='mmmu-pro' ),86.1,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15');

INSERT INTO `scores` (`modelId`,`benchmarkId`,`rawScore`,`rawScoreSecondary`,`secondaryLabel`,`benchmarkVersion`,`sourceType`,`sourceName`,`sourceUrl`,`measuredAt`) VALUES
(( SELECT id FROM models WHERE slug='claude-opus-5' ),( SELECT id FROM benchmarks WHERE slug='mmmu-pro' ),88.6,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='mmmu-pro' ),84.8,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='kimi-k3' ),( SELECT id FROM benchmarks WHERE slug='mmmu-pro' ),87.9,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='qwen3-8-max' ),( SELECT id FROM benchmarks WHERE slug='mmmu-pro' ),88.1,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='mmmu-pro' ),88,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-fable-5' ),( SELECT id FROM benchmarks WHERE slug='mmmu-pro' ),63.5,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gemini-3-5-flash' ),( SELECT id FROM benchmarks WHERE slug='mmmu-pro' ),83.4,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-mythos-5' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),81.1,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-opus-5' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),78.1,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='kimi-k3' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),77.9,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-6-luna' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),73,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),71.2,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-5' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),71,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gemini-3-7-flash' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),66.4,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='glm-5-2' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),63.8,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),63.6,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='hy3' ),( SELECT id FROM benchmarks WHERE slug='livecodebench' ),63.5,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-opus-5' ),( SELECT id FROM benchmarks WHERE slug='simpleqa' ),93.4,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-6-sol' ),( SELECT id FROM benchmarks WHERE slug='simpleqa' ),83.6,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='muse-spark-1-1' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),93.4,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-opus-4-8' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),87.6,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='glm-5-2' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),82.5,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-opus-4-6' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),82.7,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),71.1,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='grok-4-6' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),70.6,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-6-terra' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),82.2,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-6-luna' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),81.6,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gemini-3-pro' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),71.2,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='minimax-m3' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),65.9,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='inkling' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),69.1,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='mimo-v2-5-pro' ),( SELECT id FROM benchmarks WHERE slug='mmlu-pro' ),70.7,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='qwen3-7-max' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),85.8,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='qwen3-7-plus' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),87.5,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-5' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),85,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gpt-5-6-terra' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),83.8,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='claude-opus-4-5' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),86.6,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='gemini-3-pro' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),27.5,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='grok-4-5' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),50.5,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15'),
(( SELECT id FROM models WHERE slug='inkling-small' ),( SELECT id FROM benchmarks WHERE slug='arc-agi-2' ),37.1,NULL,NULL,NULL,'third_party','BenchLM BenchAlign v5 snapshot','https://benchlm.ai/','2026-08-15');

INSERT INTO `releases` (`modelName`,`provider`,`headline`,`releasedAt`,`sourceUrl`) VALUES
('GLM-5.3','Z.AI','Z.AI ships GLM-5.3 with agentic coding gains.','2026-08-14','https://z.ai/blog'),
('DeepSeek V4 Pro 0813','DeepSeek','DeepSeek publishes the V4 Pro agent-benchmark suite.','2026-08-13','https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro'),
('Gemini 3.7 Flash','Google','Google refreshes the Flash tier.','2026-08-13','https://blog.google/products/gemini/'),
('Grok 4.6','xAI','xAI reports GDPval-AA 1753 and Harvey LAB 15.8%.','2026-08-14','https://x.ai/news/grok-4-6'),
('RSI Index','Vals AI','Vals AI launches a recursive-self-improvement research index.','2026-08-13','https://www.vals.ai/home'),
('Claude Opus 5','Anthropic','Anthropic evaluated across the Vals benchmark suite.','2026-07-23','https://www.anthropic.com/news'),
('Kimi K3','Moonshot AI','Moonshot reports BrowseComp 91.2%.','2026-07-16','https://www.kimi.com/blog/kimi-k3'),
('GPT-5.6 Sol','OpenAI','OpenAI reports BrowseComp 92.2% and OSWorld 2.0 62.6%.','2026-07-09','https://openai.com/index/gpt-5-6/');